SELECT
    O.ZIP,
    COUNT(P.COST)
FROM 
    (SELECT L.OKEY AS LKEY FROM LINEITEM L) L,
    PART P,
    ORDERS O
WHERE
    L.LKEY = P.PKEY AND
    L.LKEY = O.OKEY AND
    O.ZIP <> 3800
GROUP BY O.ZIP
ORDER BY COUNT(P.COST) DESC
LIMIT 20;